incubateur-ademe/nosgestesclimat

data/divers.yaml
data/total.yaml

Parce que autres, qui commence par la même lettre que alimentation, fait
planter notre URL de partage des résultats, et qu'on veut la garder
brève

Renommage de "autres" en "divers"

---

data/divers.yaml

Pourquoi ? Parce que le code de l'interface repose sur ce préfixe pour
classer les questions en groupes et leur donner une icône de groupe.
@glm-mrt j'avais oublié cette contrainte qui est importante pour l'affichage

:bug: Préfixage des postes 'divers'

---

data/transport.yaml

Fixes #225 
Avant de commenter, il faut lire cette discussion: https://github.com/betagouv/ecolab-data/issues/225#issuecomment-689472950.
Le changement principal est celui-ci : https://github.com/betagouv/ecolab-data/pull/674/commits/cd8a171954aa73e709b916c17b3cfffa417d89fb
A tester sur https://ecolab.ademe.fr/apps/climat/?branch=amortissement-voiture

Amortissement voiture

---

data/actions/humour.yaml
data/actions/index.yaml

@laem, avec @Benjamin-Boisserie-ABC on se disait que cela pouvait valoir le coup d'ajouter une action non chiffrée de ce genre pour aussi indiquer l'importance de partager (pour aller chercher des tco2 chez les autres aussi !)
Cela sera-t-il possible de faire apparaître cette action même si elle ne rentre dans aucune catégorie précédente (et d'autres de ce genre ? éventuellement sans impact comme se balader ...) dans le listing final ?
Peut-être faut-il scinder en 2 : 
- humour (actuel) : pour la doc
- autre : pour des actions en plus de ce genre
Qu'en penses-tu ?

Action partage NGC

---

data/actions/transport.yaml

Modif titre : pour coller au titre de la fiche élaborée et car "adopter" semble plus usuel que "faire"
Modif contenu : pour réduire le texte qui était trop long

Fiche simple : éco-conduite (modif titre et contenu)

---

data/logement.yaml

On reste en kWh mais on donne un indice de performance énergétique du kg de granulés.
Voir https://github.com/betagouv/ecolab-data/issues/512
NB : Le mieux serait d'intégrer le chiffre dans le calcul (4 600 kWh/t)
https://www.ademe.fr/etude-chauffage-domestique-bois

Proposition de fix simple pour aider à la saisie des granulés.

---

CONTRIBUTING.md

Mise à jour d'un ancien lien cassé

---

data/logement.yaml

Le message dans la description ne me semble plus adéquat étant donné que pour la conso de bois en bûche on ne se réfère plus à l'onglet "Calcul consommation Energie" du tableur MicMac. Le message de description étant donc un peu embrouillant.

descritption bûche.estimation via le coût

---

data/actions/transport.yaml

Le facteur de correction se situe plutôt à **15 %** cf. Guide de Formation à l’éco-conduite (https://www.ademe.fr/sites/default/files/assets/documents/66885_guide_ecoconduite.pdf) page 8
Le facteur 20 % qui était donné dans le guide ADEME (10 questions sur la mobilité) reprend un chiffre donné dans le guide de formation venant de l'expérimentation du groupe La Poste ou la réduction d'émissions de GES varie de 4 à 20 %

correction facteur éco-conduite

---

data/transport.yaml

> L'objectif : ne pas considérer qu'une voiture (construction comme empreinte au km) a la même empreinte qu'elle soit une twingo/zoé ou un SUV/Tesla.
Fixes #540
v1 sans extrapolation d'empreinte en fonction du poids
Voilà nos données, qui me semblent suffisantes pour une v2 du calcul bien meilleure que notre bête tableau actuel : 
Bilan-GES : https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=voiture
Etude FNH-C4
- [zip original](www.fondation-nicolas-hulot.org/sites/default/files/vehicule_electrique_rapport.zip).
- [pdf](https://github.com/betagouv/ecolab-data/files/5945898/vehicule_electrique_rapport.pdf)
Gabarit - poids, à extrapoler pour obtenir les gabarits manquants (2 c'est trop peu pour l'utilisateur).
p.12 
p. 35
p. 57
p. 58

Ajout du gabarit de la voiture

---

data/divers.yaml

1er jet pour lister les différents bien électroménager d'un individu. L'idéal serait d'avoir la même forme que pour le listing des biens d'équipements électroniques (case à cocher)
Connaitre le détail des biens permettra d'affiner l'estimation carbone du poste divers et permettra de créer certaines actions (allongement durée de vie, séchage air libre, etc.)

listing biens électroménagers

---

data/actions.yaml
data/alimentation/actions/alimentation.yaml
data/alimentation/alimentation.yaml

A voir si on l'insère cette question sur le gaspi alimentaire car il s'agit en quelque sorte d'un double comptage avec ce qui est comptabilisé dans la variable déchets.
Cependant, cela est plus logique de trouver cette question ici (que dans le volet action) et de proposer directement une action en fonction de la réponse.
Dans l'idéal, il faudrait retravailler l'évaluation GES de la partie déchets en essayant de sortir la partie propre au gaspi alimentaire qui elle serait traitée via cette question

Ajout question gaspillage alimentaire

---

data/alimentation/actions/alimentation.yaml
data/alimentation/alimentation.yaml
data/transport/actions/transport.yaml
data/transport/transport . voiture.yaml
data/transport/transport.yaml

Quelques retours rapidement "corrigeables" suite à l'atelier "ADEME 30 ans" :

Retours suite atelier convention

---

data/divers/actions/divers.yaml
data/transport/actions/transport.yaml

C’est une modification mineure, mais je trouvais intéressant de compléter l’explication qui proposait d’installer des applications alternatives sans publicités : il existe des bloqueurs de pub généraux, qui vont aussi bloquer les publicités dans des applications qui en ont normalement (il bloque l’accès à ses applications à des sites de publicité).

Ajout d’un lien vers un bloqueur de pub

---

data/conversion-métrique.yaml
data/transport/transport . voiture.yaml

Pour faire suite à nos discussions @laem et @Benjamin-Boisserie-ABC j'ai ajouté une notification d'avertissement pour les biocarburants. (lié à #1324)
Personnellement, je ne suis pas satisfait de la solution. J'ai l'impression qu'on pourrait écrire cette notification sur plusieurs questions au vu des incertitudes des FE dans la base carbone... Je suis complètement d'accord de ne pas proposer l'action "passer aux biocarburants" à causes des enjeux associés mais pas d'accord de ne pas proposer ce qui est disponible (même imparfait). Oui on a matière à critiquer ce chiffre mais pourquoi ne pas prendre en compte le FE actuel en mentionnant ce dit la base carbone ? Le périmètre de NGC est le bilan GES de mon point de vue...
> Les travaux existants ou en cours n’ont pas encore réussi à créer …

Notification biocarburants

---

.github/workflows/pr-comment.yaml
.github/workflows/upload-compilation-result.yaml

Fixes the initial PR #1463 to support pull requests from forked repositories.
**Why?**
For security reasons, pull request comments can't be edited from a workflow triggered by a forked repository -- see https://github.com/datagir/nosgestesclimat/pull/1339#issuecomment-1232733140.
**Solution**
To bypass this issue, this PR setups a new workflow which uploads the result of the model compilation as an artifact which is read by [another workflow](https://github.com/datagir/nosgestesclimat/blob/master/.github/workflows/pr-updater.yaml) in the main repository, before updating the comment in the corresponding PR.
* New GitHub Action: `upload-compilation-result.yml`

ci: fix GH Action from forked repositories

---

data/translated-rules-en-us.yaml
data/transport/transport . avion.yaml

En travaillant sur l'i18n, la question avion est une des seules spécifique à la France. 
On s'est rendu compte qu'il serait mieux de raisonner en vols de moins de x heures plutôt que de décrire des zones géographiques, à la fois pour l'i18n et pour l'UX. 
De plus, nos définitions des distances semblent remises en question.

Réécriture des questions avion

---

docs/Home.md
docs/_Sidebar.md
docs/translation.md
package.json
scripts/i18n/cli.js
scripts/i18n/regionCommons.js
scripts/i18n/translateRegionModel.js
scripts/i18n/utils.js
scripts/rulesToJSON.mjs
yarn.lock

Implement the v0 of #1710.
* New `translateRegionModel.js` script.
* Move code related to region models into a separate file.
* Use a custom logger to avoid polluting the rulesToJSON's output.

Feat(scripts/i18n): add v0 translation scripts for region models

---

data/i18n/t9n/translated-rules-en-us.yaml
data/transport/actions/transport.yaml
package.json
scripts/i18n/check-translation.js
scripts/i18n/cli.js
scripts/i18n/regionCommons.js
scripts/i18n/translate-rules.js
scripts/i18n/translateRegionModel.js
scripts/rulesToJSON.mjs
yarn.lock

Start to implement some of the tasks listed in the meta issue https://github.com/datagir/nosgestesclimat-site/issues/782.
https://user-images.githubusercontent.com/44124798/223399694-5ba0e4cd-b4f8-407d-a067-783c14297044.mp4
- New `--only-update-locks` flag for rules translation -- closing https://github.com/datagir/nosgestesclimat-site/issues/871.
- New `--interactive-mode` flag for rules translation.
- Remove the `regionCommons.js` dependency from `cli.js` -- which are used by the scripts in the website repository.
- Add missing translation -- fixing #1765 
- Remove the progress bar for the rule translation.
- Replace the `inquirer` dependency by the simpler one `prompt-sync` for user interaction in the CLI.

Feat(scripts/t9n): improvement on the rule translation workflow

---

data/divers/divers.yaml
data/i18n/t9n/translated-rules-en-us.yaml

Le FE de la base carbone est en kgC02e/€HT. L'input de la question dépenses est en €TTC. Il est nécessaire d'avoir un FE en  kgC02e/€HT 
Je merge directement, c'est une grosse erreur de ma part @lbranaa @Benjamin-Boisserie-ABC @laem

TVA ratio monétaire

---

personas/personas-fr.yaml

#1784 mettait en valeur des deltas importants au niveau de certains personas, l'idée est de checker dans cette PR que ces différences sont bien liées aux changement des règles appareils `. présent` en `. nombre` mais dont le changement n'a pas été répercuté dans les personas (lié à #1791)

Fix personas règles appareils numérique

---

data/i18n/t9n/translated-rules-en-us.yaml
data/logement/logement.yaml
personas/personas-en-us.yaml
personas/personas-fr.yaml

Une erreur fréquente sur Sentry, qui créée une page blanche permanente
sans effacement de localstorage, d'où l'urgence.
Cette PR provoque une nouvelle question pour tous ceux qui avaient déjà un test rempli. 
Un exemple clair de nécessité de script de migration.

On évite une division par zéro pour le nombre d'habitants

---

data/logement/logement.yaml

Fix #1838 
Un bug cassant apparait lorsque l'on ajoute plusieurs chiens différents : derrière on utilise le mécanisme `recalcul`
D'un autre côté, on amorti l'empreinte des animaux via le nombre d'habitants via la variable `logement . habitants` qui utilise le mécanisme `le maximum de`
Les 2 mécanisme "couplés" semble provoquer le bug, c'est curieux ..
Studio [ici](https://publicodes.vercel.app/document/calymmien-d%C3%A9gueulasse-surfil%C3%A9?target=divers%20.%20animaux%20domestiques%20.%20empreinte)

Bug mécanisme "le maximum de"

---

data/i18n/t9n/translated-rules-en-us.yaml

Les plaques vitroceramiques étaient traduites littéralement en "plates" hors plates signifie "assiettes" et non plaques de cuissons.
Le terme correcte étant "cooktop" ou "stove" (mais il me semble que ce dernier est plus général (inclus aussi les fours ou poêles à bois/gaz)  
Le terme "cooking plate" à été remplacé par "cooktop" dans la traduction anglaise

Correction de la traduction de "plaques vitroceramiques"

---

scripts/rulesToJSON.mjs

Fixes #1889 by logging the [compilation error](https://github.com/datagir/nosgestesclimat/actions/runs/5066606513/jobs/9096618380?pr=1890) in the CI output and by compiling rules before running personas and optim tests:

Fix: better error message in the CI when the rulesToJSON fails at parsing

---

data/i18n/models/GF-en-us.yaml
data/i18n/models/GF-fr.yaml
data/i18n/models/GP-en-us.yaml
data/i18n/models/GP-fr.yaml
data/i18n/models/MQ-en-us.yaml
data/i18n/models/MQ-fr.yaml
data/i18n/models/PF-en-us.yaml
data/i18n/models/PF-fr.yaml
data/i18n/models/RE-en-us.yaml
data/i18n/models/RE-fr.yaml
data/i18n/models/YT-en-us.yaml
data/i18n/models/YT-fr.yaml

L'ajout du ferry n'avait pas été répercuté dans les modèles outre-mer dans lesquels nous avions réécrit la formule de `transport . empreinte` pour éliminer le train.
(ping @JuliePouliquen)

Ajout ferry transport régions outre-mer

---

data/actions.yaml
data/conversion-métrique.yaml
data/i18n/models/GF-en-us.yaml
data/i18n/models/GF-fr.yaml
data/i18n/models/GP-en-us.yaml
data/i18n/models/GP-fr.yaml
data/i18n/models/MQ-en-us.yaml
data/i18n/models/MQ-fr.yaml
data/i18n/models/PF-en-us.yaml
data/i18n/models/PF-fr.yaml
data/i18n/models/RE-en-us.yaml
data/i18n/models/RE-fr.yaml
data/i18n/models/YT-en-us.yaml
data/i18n/models/YT-fr.yaml
data/i18n/t9n/translated-rules-en-us.yaml
data/transport/actions/transport.yaml
data/transport/transport.yaml
personas/personas-fr.yaml

Répond en partie à #966 et à #1884.
Fait : ajout de l'option "scooter électrique" parmi les choix de deux-roues motorisés.
Modification du nombre de km / défaut pour les motos.
Reste à faire :

Ajout du scooter électrique dans la liste des choix de deux-roues

---

scripts/i18n/utils.js

Petit pb au niveau des scripts de traduction suite à l'ajout du ferry ou nous avons intriduit une subtilité sur la possibilité d'écraser un attribut du modèle source avec une valeur `null` (c'est le cas pour les questions que l'on ne souhaite pas afficher dans le test). Le fix ici permet de ne pas passer ces attributs dans les règles à traduire.
Dans le modèle, c'est néanmoins impossible *de base* d'avoir un attribut vide donc je ne sais pas comment on souhaite gérer ce cas particulier

Un attribut vide ne doit pas être traduit

---

data/divers/divers.yaml
data/i18n/t9n/translated-rules-en-us.yaml

La TVA s'applique sur le montant des dépenses fait en TTC (pour repasser en HT la dépense) et non pas sur la valeur du ratio monétaire

Correction application TVA

---

package.json
scripts/i18n/translate-rules.mjs

Suite à #2006 
* Switch script `translate-rules` depending on `@incubateur-ademe/publicodes-tools` to `.mjs`.

Migrate translate-rules script to mjs

---

data/transport/transport.publicodes
package.json
yarn.lock

Re-enables the `ferry` question by using the patched `@incubateur-ademe/publicodes-tools` -- see: https://github.com/incubateur-ademe/publicodes-tools/pull/20
- Upgrade `@incubateur-ademe/publicodes-tools` to `v0.2.1`
- Re-enables the ferry question.

Fix(data): re-enable the `ferry` question

---

contenu-ecrit/guide-mode-groupe/guide.md

Les liens vers les pages guides par catégories ne fonctionnent plus côté migration NextJS. Je les mets donc à jour ; une autre PR est en cours côté site pour gérer cette modification dans l'app actuelle.

Modification des liens

---

data/i18n/t9n/translated-rules-en-us.yaml
data/transport/transport . ferry.publicodes

Assez mystérieusement, on a un souci avec le persona Marie actuellement : si on sélectionne le persona moyen (situation vide), en allant sur la page "Profil", l'app casse avec cette erreur :
Il ne me semble pas que ce soit un pb d'optim dans la mesure ou je teste avec l'optim désactivée..
En important la règle manquante depuis futureco, j'ai l'impression que le problème est résolu .. C'est peut etre lié au fait qu'on importe les enfants de `ferry . surface` sans importer leurs parents mais je trouve que la manière dont arrive ce bug est étrange

🐛 Fix: bug persona Marie sur la page Profil

---

README.md
data/actions/alimentation.publicodes
data/actions/archives/humour.archive
data/actions/divers.publicodes
data/actions/logement.publicodes
data/actions/transport.publicodes
data/alimentation/boisson.publicodes
data/alimentation/déchets.publicodes
data/bilan.publicodes
data/divers/numérique.publicodes
data/empreinte SDES/empreinte nationale.publicodes
data/i18n/t9n/translated-rules-en-us.yaml
data/logement/chauffage.publicodes
data/logement/chiffres parc logements français.publicodes
data/logement/climatisation.publicodes
data/logement/construction.publicodes
data/logement/logement.publicodes
data/logement/prix du gaz.publicodes
data/logement/électricité.publicodes
data/transport/bus.publicodes
data/transport/métro ou tram.publicodes

Fix #2077 
Migration de tous les liens de `références` dans les notes
On avait également des erreurs via l'ajout de liens dans `reference` ou `références` qui ne sont pas des mécanismes publicodes.

[clean] plus `références` dans le modèle

---

data/logement/chauffage.publicodes
personas/personas-fr.yaml

Fix #2128
Fix #2129 
Un bon exemple de cas non couvert que les tests de personas auraient permis de détecter ;)
Ici avant l'ajout du %:

Gestion du % dans la question biogaz (NGC-156)

---

build.mjs
package.json
yarn.lock

The problem is that parsed rules from the engine use by the `constantFolding` function was [modified in place](https://github.com/publicodes/tools/pull/31) and this was a problem when called multiple times (I don't know why honestly).
This fixes https://github.com/publicodes/tools/issues/30 and improves some rule optimisations btw.
> [!IMPORTANT] 
> Doing a deep copy of the parsed rules noticeably degrades compilation performance. Therefore, this **should be considered as a temporary fix** while waiting to improve `constantFolding`.
> 
> `yarn compiles:rules`: from ~28s to 36s
> `yarn compiles:rules -o FR -t fr`: from ~3.71s to ~4.33s

Fix the crash in the compilation script in sync mode - [NGC-110]

---

data/i18n/t9n/translated-rules-en.yaml
data/transport/métro ou tram.publicodes

Pas si évident : la vitesse des RER est vraiment plus importante que le métro / tram. Le fait d'inclure l'impact du RER dans la question peut surestimer son empreinte (je fais plus de km en moins d'heures)
Preneur de votre avis @JuliePouliquen @mquandalle

Ajoute le RER dans le calcul `métro ou tram` (NGC-312)

---

.github/workflows/upload-compilation-result.yaml
package.json
scripts/i18n/addTranslationToBaseRules.js
tests/testTranslation.mjs

Removes `.auto` and `.previous_review` attributes from the translated rules and fix a problem with *inlined* rules (i.e `rule: oui`) translation. It adds a new `testTranslation` script that compares result for each rule between `fr` and `en` models.

Fix(t9n): correctly translate rules

---

data/actions/alimentation.publicodes
data/i18n/t9n/translated-rules-en.yaml

Correction par un recalcul qui ne transforme que les plats viande et poissons en plats végés, et non l'intégralité des 14 repas.

Correction action passer végé - NGC-540

---

.github/dependabot.yml

Pour avoir seulement des PR pour ce qui concerne les dépendances publicodes

allow only publicodes dependencies in dependabot

---

data/alimentation/repas.publicodes
data/i18n/t9n/translated-rules-en.yaml
data/i18n/t9n/translated-rules-es.yaml
package.json

Une erreur s'était introduite dans le fichier Excel : les données pour le dessert n'étaient pas bonnes, et le repas poisson était délesté de quelques 300gCO2e / repas.

Fix FE poisson NGC-878

---

data/logement/électricité.publicodes

L'indication parlait de Wc, quand l'unité attendue était du kWc. Un facteur 1000 qui n'aide pas à s'y retrouver.

Fix unités aide saisie - NGC-935

---

.github/workflows/pr-updater.yaml
.github/workflows/upload-compilation-result.yaml
data/alimentation/repas.publicodes
data/i18n/t9n/translated-rules-en.yaml
data/i18n/t9n/translated-rules-es.yaml
package.json

Cette mise à jour est devenue prioritaire quand on a réalisé qu'elle divisait plus ou moins par deux l'empreinte eau des repas.

Mise jour données Agribalyse NGC-1078

---

index.d.ts

This PR fixes the `NGCRule` type to match the exported rules

:label: NGCRule
