incubateur-ademe/nosgestesclimat

- co2.yaml
Ici on suit l'avancement de l'implémentation de la version 0.
Nous avons exclu la variation de facteur d'émission de l'électricité verte, voir #4.
- Soit on fait comme dans le tableur, pour une voiture en plus diviser par 2 l'âge de la 1ère, mais c'est contre-intuitif, et ça ne correspond que au cas 2 voitures pour 1 personne. 
- soit on fait passer le message qu'avoir 2 voitures c'est mal.
- Soit on ignore le poids carbone de la 2ème voiture. 
- Soit on laisse saisir la 2ème voiture et on moyenne leur empreinte * kilomètre.
- Soit on fait permet vraiment la gestion de son parc, voiture par voiture, ce qui demande à faire évoluer publi.codes, mais ça me semble trop lourd pour un cas rare.
On peut soit les mettre à 0 partout, soit choisir la valeur la plus probable en itérant et en …
> Simu climat annuelle v0

- co2.yaml
Suite à des retours utilisateur :-)
> Rustine produits neufs & autres petits sujets

- co2.yaml
https://github.com/betagouv/ecolab-climat/issues/24
> Calcul consommation annuelle électricité

- data/numérique.yaml
> Précision calcul numérique

- data/transport.yaml
Dans cette PR, en préparation de l'atelier de lundi 7 septembre 2020, on prépare une v2 du calcul de l'avion, plus précise.
@fjg pour mettre en ligne le + rapidement possible cette amélioration, je décale ce 2ème point à une issue future
> Avion 2 + images dans la documentation

- data/transport.yaml
> Quelques corrections sur le thème de la voiture

- data/logement.yaml
> On demande explicitement la conso en énergie du foyer

- data/actions/transport.yaml
- Attention au 52 si c'est les semaines, le ramener à 47 pour tenir compte des 5 semaines de congés.
> Maj covoiturage

- data/actions/transport.yaml
- texte source eco conduite
- maj covoiturage
> Modif texte

- data/actions/index.yaml
- data/actions/transport.yaml
- data/alimentation.yaml
Voir notamment [cette discussion](https://github.com/betagouv/ecolab-data/pull/581#discussion_r500372567)
Dispo ici https://ecolab.ademe.fr/apps/climat/?branch=action-transport-teletravail
> Action télétravail

- data/actions/index.yaml
- data/actions/transport.yaml
> Action arrêter partiellement l'avion

- data/actions/index.yaml
- data/actions/transport.yaml
> Prendre les transports en commun pour le boulot

- data/services publics.yaml
Mise à jour du FE services publics avec la dernière source la plus à jour sur le sujet : https://ree.developpement-durable.gouv.fr/themes/defis-environnementaux/changement-climatique/empreinte-carbone/article/l-empreinte-carbone-de-la-france
> Mise à jour facteur d'émission des services publics

- data/actions/transport.yaml
correction de faute d'orthographe, fixes #805
> trajets cours en vélo → trajets courts à vélo

- data/actions/logement.yaml
- data/actions/transport.yaml
- data/alimentation.yaml
- data/divers.yaml
- data/logement.yaml
- data/numérique.yaml
- data/transport.yaml
Voir https://github.com/betagouv/ecolab-climat/pull/135
> Adaptation du modèle au nouveau publicodes

- data/transport.yaml
> Durée de vie moyenne des voitures françaises

- data/alimentation.yaml
- data/divers.yaml
- data/logement.yaml
> Petites améliorations, dont aide à la saisie de questions

- data/logement.yaml
Suite à plsueiurs retours utilisateurs.
Fixes #409
> Meilleure saisie de la consommation de bois de bûche

- data/actions/transport.yaml
- data/transport.yaml
Fixes #826
Fixes #809 
Fixes #804
Fixes #810
Fixes #802
Fixes #795
Fixes #763
Fixes #759
Fixes #74
> Ajout de la possibilité vélo pour aller au travail autrement qu'en voiture

- data/transport.yaml
Fixes #184 
Pas de 2 roues électriques, pas d'empreinte de construction, on commence petit mais 90% des usages et de l'empreinte semble couverte :)
> Nouvelle question : moto

- data/transport.yaml
- Note sur "pas de voiture individuelle" puis "quelle motorisation"
-
> Petites améliorations

- data/actions/alimentation.yaml
- data/actions/index.yaml
> @Benjamin-Boisserie-ABC je reprends les travaux de la branche `Benjamin-ABC-actions` pour les intégrer proprement, action par action (ou en groupe d'actions similaires) avec donc une PR pour chaque action (c'est important pour qu'on s'y retrouve)
Pour viande / 4, voir ce brouillon : https://github.com/betagouv/ecolab-data/pull/581/files#diff-6413ed253e9ecf556b94e58c5d7eef8d9a8ac03fa3f4ac7835804f2a195d0050
> Actions de réduction de viande

- data/numérique.yaml
> Numérique mosaïque

- data/actions/index.yaml
- data/actions/logement.yaml
- data/logement.yaml
1er version de l'action consistant à remplacer une chaudière fioul par une au bois
> remplacement chaudière fioul par bois

- data/actions/divers.yaml
- data/actions/humour.yaml
- data/actions/index.yaml
- data/actions/services publics.yaml
- data/divers.yaml
- data/transport.yaml
@Benjamin-Boisserie-ABC @martinregner j'ajoute deux actions qui ciblent évidemment sans chiffres la catégorie services publics :)
> Actions services publics

- data/alimentation.yaml
Je propose une nouvelle formulation de la question sur le lait car elle me semblait confuse #274
> remplacement question lait

- data/logement.yaml
Une amélioration qui a trop tardé.
Fixes  #735
Fixes #111
Fixes #983
Fixes #897 
Fixes #209
Fixes #969
> âge logement

- data/actions/index.yaml
- data/actions/logement.yaml
En complément de ça il y a probablement de nombreux éco-gestes ménagers à implémenter (mais peut être pas tous quantifiables)
> séchage à l'air libre

- data/actions/index.yaml
- data/actions/transport.yaml
> Petits trajets en voiture

- data/actions/index.yaml
- data/actions/logement.yaml
- public/images/ecolab-climat-dessin2.svg
Dans une deuxième approche éventuellement proposer à l'utilisateur par quoi il veut remplacer sa chaudière (bois ou PAC) ?
> remplacement gaz par PAC

- data/transport.yaml
> Précision thermique = diesel ou essence

- data/actions/transport.yaml
Ainsi que MAJ de l'empreinte en se basant sur monimpacttranport
> Aération des textes des actions éco-conduite et avion->train

- data/actions/transport.yaml
Suppression de l'unité "km" dans la question "fréquence des déplacements de moins de 5km"
> correction coquille

- data/alimentation.yaml
- data/divers.yaml
- data/logement.yaml
- data/numérique.yaml
- data/transport.yaml
Voir https://github.com/datagir/nosgestesclimat-site/pull/296
> Notifications

- data/transport.yaml
> Documentation des voyageurs voiture : cas du taxi

- data/logement.yaml
Je ne sais pas comment faire pour que le code choisisse entre la donnée de "consommation" ou "consommation litre". Voila ce que j'avais imaginé
> consommation fioul en litre

- data/divers . textile.yaml
Une PR qui complète la 1ère suite aux remarques de @martinregner ici #1125
> Mosaique textile

- data/actions.yaml
- data/divers/actions/divers.yaml
Action non quantifiée car : 
1) c'est quasi impossible de le faire sans une étude approfondie
2) le but ici est de passer un message et de mettre en avant quelques exemples clés
> Action ignorer pub et soldes

- data/actions.yaml
- data/alimentation/actions/alimentation.yaml
- data/alimentation/alimentation.yaml
> Prise en compte du menu poisson dans les actions alimentation

- data/actions.yaml
- data/divers/actions/divers.yaml
On utilise la règle publicodes recalcul pour cette action (PR #1003)
> Action allongement durée de vie électroménager V2

- data/transport/transport.yaml
Pour https://github.com/datagir/nosgestesclimat-site/pull/409
> Aide calcul transport côté modèle

- data/logement/logement.yaml
- data/logement/prix du gaz.yaml
> maj prix du gaz

- data/transport/transport . voiture.yaml
https://docs.google.com/spreadsheets/d/1TMe_49JW0djDFHLtejWcIs3CRCt4vh3PJUvm7NtH0co/
> Changement ratio voyageurs

- data/transport/actions/transport.yaml
- Typos légères
- Ajout d'un lien vers mesaidesvélo dans les actions pertinentes
L'outil est développé par @mquandalle, qui est développeur sur mon-entreprise.fr, et mesaidesvelo est déjà intégré sur le site officiel https://www.1jeune1solution.gouv.fr.
> Ajout de mesaidesvelo.fr dans les actions

- data/logement/logement.yaml
Suite à une discussion à propos des modes de chaleur et en attente de #872 et #1357 :)
Je n'ai pas réussi à mettre en place de notification comme évoqué dans les issues, même en rajoutant ce bloc ..:
```yaml
logement . chauffage . PAC . notif:
type: notification
formule:
toutes ces conditions:
- présent = oui
description: |
Vous avez renseigné "pompe à chaleur", sa consommation électrique sera prise en compte dans votre consommation globale d'électricité. 
```
> Ajout modes chauffage

- data/alimentation/alimentation.yaml
- data/conversion-métrique.yaml
- data/transport/actions/transport.yaml
Correctifs des deux PR [ MAJ facteur d'émission + pétrole ] mergées trop rapidement :/
> :bug: Oublie de maj d'une action suite à changement variable commune

- data/divers/divers . électroménager.yaml
- data/numérique/numérique.yaml
- data/personas.yaml
Afin d'éviter de poser la question de l'age de l'appareil pour chaque appareil coché, voici une transposition du "modèle électroménager" au numérique.
Toutes les durées de vies théoriques sont de 10 ans car je n'arrive pas à retrouver dans les études ADEME la durée d'usage considérée pour tous les produits numériques (à l'exception du vidéoprojecteur ou j'ai trouvé une durée d'usage de 8 ans)
J'ai aussi rajouter les équipements (car ce nouveau modèle permet moins de questions et plus de choix) : 
- enceinte Bluetooth
- enceinte à commande vocale
- montre connectée
> MAJ modèle numérique

- data/alimentation/alimentation.yaml
Pour appliquer les réflexions de l'issue #1375
Aujourd'hui, on ne s'appuie pas sur une étude/enquête.
> Changement de la répartition repas

- data/guide-mode-groupe/guide-alimentation.md
- data/guide-mode-groupe/guide-transport.md
Quelques petits correctifs après avoir parcouru la documentation.
> Correction de typos dans le guide

- CONTRIBUTING.md
- data/alimentation/alimentation.yaml
Solution pour la contribution en ligne !
@Benjamin-Boisserie-ABC tu peux tester ? Je suis dispo pour un point rapide si tu veux qu'on regarde ensemble !
> Ajout Gitpod

- data/alimentation/alimentation.yaml
- data/divers/divers . textile.yaml
- data/divers/divers . électroménager.yaml
- data/logement/logement.yaml
- data/services publics/services publics.yaml
- data/transport/transport . voiture.yaml
Reliée à https://github.com/datagir/nosgestesclimat-site/pull/511
- ajoute une question services publics
- change les emojis utilisés pour les catégories et sous-cat
> Question services publics

- data/alimentation/alimentation.yaml
- Déplacement des bonus saison et local dans midis et dîners
- Nouvelle variable "repas" pour regrouper matin, midi, soir et bonus
- Ajout de titres pour le SEO
> seo titres

- data/alimentation/alimentation.yaml
- Déplacement des bonus saison et local dans midis et dîners
- Nouvelle variable "repas" pour regrouper matin, midi, soir et bonus
- Lien vers mesfruitsetlegumesdesaison.fr dans l'aide à la question saison
> mesfruitsetlegumesdesaison.fr dans l'aide à la question saison

- data/actions-plus/alimentation . déchets . action.md
- data/actions-plus/alimentation . gaspillage alimentaire.md
- data/actions-plus/alimentation . réduire viande . par deux.md
- data/actions-plus/divers . déchets . recyclage.md
- data/actions-plus/divers . meubles . seconde main.md
- data/actions-plus/divers . textile . seconde main.md
- data/actions-plus/divers . électroménager . seconde main.md
- data/actions-plus/logement . baisse température.md
- data/actions-plus/logement . chaudière remplacement.md
- data/actions-plus/logement . climatisation . réduction.md
- data/actions-plus/logement . rénovation énergétique.md
- data/actions-plus/logement . éteindre appareils.md
- data/actions-plus/transport . boulot . commun.md
- data/actions-plus/transport . boulot . covoiturage.md
- data/actions-plus/transport . voiture 5km.md
- data/actions-plus/transport . éco-conduite.md
Suite de la maj des liens cassés des fiches actions-plus
> Mise à jour des images cassées suite

- data/logement/logement.yaml
> Notification amortissement logement

- data/logement/logement.yaml
- data/transport/transport . voiture.yaml
Afin d'éviter les divisions par 0 (et donc les valeurs infinies / résultats fossés) 
Démo dans cette PR : https://github.com/datagir/nosgestesclimat-site/pull/601
> Introduction d'un minimum pour certaines questions

- personas.yaml
- Ajout d'une caravane pour le persona Sandy
- Plus de mode chez le persona Nadia, moins de voiture
> pour iconographie

- data/alimentation/alimentation . boisson.yaml
> Suppression de la part de consommation dans le FE thé

- data/alimentation/actions/alimentation.yaml
- data/alimentation/alimentation . boisson.yaml
- data/alimentation/alimentation.yaml
- data/alimentation/modèle déchets/alimentation . déchets.yaml
- data/divers/divers . textile.yaml
- data/divers/divers . électroménager.yaml
- data/logement/actions/logement.yaml
- data/logement/logement.yaml
- data/numérique/numérique.yaml
- data/transport/transport . caravane.yaml
- data/transport/transport.yaml
Soeur côté site : https://github.com/datagir/nosgestesclimat-site/pull/661
> Mosaïques dans le modèle !

- data/divers/divers.yaml
- data/logement/climatisation.yaml
- data/logement/logement.yaml
Premier modèle de @Benjamin-Boisserie-ABC sur la base de ceux de @samgwada.
Sam n'avait pas mis le modèle en publicodes. Voici ses notes.
> Modèle d'empreinte de la climatisation

- .github/workflows/upload-compilation-result.yaml
- data/logement/biogaz.yaml
- data/logement/logement.yaml
Je remarque qu'il n'y a qu'un seul fournisseur de 100%, anecdotique, mais que le géant Engie propose une part variable.
> Ajout de la question biogaz

- personas.yaml
Quelques modifications dues aux changements de certaines variables chauffage, les valeurs par défaut et l'ajout de la clim.
> Maj personas suite PR chauffage & climatisation

- data/logement/logement.yaml
Pour itérer sur la question des types d'énergie dans le logement et sa description
> Proposition précision question chauffage

- data/logement/actions/logement.yaml
- data/logement/chiffres parc logements français.yaml
Actuellement, il y a un problème pour la quantification des actions si les réponses pour le chauffage sont par défaut. J'en profite pour mettre à jour avec les valeurs du parc français les parts de chauffage dans les conso totales de chaque type d'énergie
> Maj variables chauffage dans les actions

- data/alimentation/alimentation . boisson.yaml
- data/alimentation/alimentation.yaml
Itération concernant le travail mené dans #1266 
Google sheet de travail : https://docs.google.com/spreadsheets/d/1SVYvBaaYDOUDcg5jX0eZFEColnWWIL8PCLMGrPR000o/edit#gid=439425648
> Mise à jour FE repas alimentation

- data/divers/actions/humour.archive
L'idée était de détendre l'atmosphère sur cette page /actions très engageante, avec des calculs "débiles" pour montrer au passage l'ordre de grandeur des faibles actions nécessaires (utiliser un ordinateur pour s'informer, c'est un bon investissement).
On ne l'a jamais fait, je la garde en archive (donc pas exposée sur le site) pour l'inspi, quelqu'un fera peut-être mieux un jour
> Cette action n'a jamais été mise en ligne

- data/logement/climatisation.yaml
Suite aux remarques sur la climatisation remontées dans [cette vidéo](https://youtu.be/e8uN9nR50TY?t=983), je propose ces modifications :)
> Précisions question climatisation

- data/alimentation/alimentation.yaml
- data/translated-rules-en-us.yaml
- data/translated-rules-es.yaml
- data/translated-rules-it.yaml
- scripts/i18n/utils.js
Partially fixes https://github.com/datagir/nosgestesclimat-site/issues/723
> fix(t9n): fix markdown table for alimentation

- data/numérique/numérique.yaml
- data/translated-rules-en-us.yaml
> fix(data/t9n): add missing translation of the smartphone types

- data/logement/logement.yaml
Proposition pour que la valeur par défaut de la consommation d'énergie liée au chauffage tienne compte de la surface du logement
> variabilisation des valeurs par défaut conso chauffage

- personas/personas-fr.yaml
> Partially fixes https://github.com/datagir/nosgestesclimat-site/issues/780
> fix(personas): add missing rules to properly evaluate personas' model

- data/numérique/numérique.yaml
Accent en trop dans précocement. Précocément --> précocement
> Mini typo numérique

- data/divers/divers . électroménager.yaml
> Typo électroménager

- data/logement/logement.yaml
Quelques typos dans les questions logement
> Typos questions logement

- data/alimentation/alimentation.yaml
Je propose de changer le terme "midi" en "déjeuner", qui est l'homologue de "diner" :)
> Midis --> déjeuners

- data/alimentation/alimentation.yaml
Petites typos ou mots manquants dans les descriptions des petits dej
> Typos descriptions petits dej

- data/transport/transport . avion.yaml
> Question long courrier rajout d'un mot

- contenu-ecrit/guide-mode-groupe/guide.md
Différentes typos dans le texte + j'ai rajouté certains espaces manquants
> Typos guide animateur

- data/alimentation/alimentation.yaml
L'ordre (si je ne me trompe pas) est : 
- question boissons chaudes
- question petit-déjeuner Donc lors de la question petit-déjeuner, il faut dire que les boissons ont été comptabilisées précédemment (et non pas qu'elles le seront ultérieurement)
> MAJ note petit-déjeuner

- package.json
- scripts/i18n/addTranslationToBasePersonas.js
- scripts/i18n/addTranslationToBaseRules.js
- scripts/i18n/utils.js
- yarn.lock
Replacement of AssocPath function from ramda was not behaving as expected, for array of attributes for instance.
Here I introduce custom functions to deals with paths in Object.
> Introduce custom assocPath function

- .github/workflows/upload-compilation-result.yaml
- package.json
- scripts/modelOptim.mjs
- scripts/rulesToJSON.mjs
- yarn.lock
> Rulestojson esm

- data/conversion-métrique.yaml
- data/i18n/t9n/translated-rules-en-us.yaml
- data/logement/prix du gaz.yaml
Mise à jour du prix du gaz en fonction des tarifs 2023
J'ai également remis les liens des sources à jour.
> MAJ prix gaz 2023

- data/alimentation/alimentation . boisson.yaml
- data/alimentation/alimentation.yaml
- data/commun.yaml
- data/conversion-métrique.yaml
- data/divers/divers.yaml
- data/i18n/t9n/translated-rules-en-us.yaml
- data/logement/actions/logement.yaml
- data/numérique/actions/numérique.yaml
- data/numérique/numérique.yaml
- data/transport/actions/transport.yaml
- data/transport/transport.yaml
> Introduction d'un fichier de règles communes

- package.json
- scripts/i18n/cli.js
- scripts/i18n/translate-rules.js
- yarn.lock
Closes #1771 part of https://github.com/datagir/nosgestesclimat-site/issues/782.
* Improve the interactive mode of the rule translation
* New dev dependency: `git-diff`
> feat(script/t9n): print diff in the interactive mode of the rule translation

- data/i18n/t9n/translated-rules-en-us.yaml
Related issues : https://github.com/datagir/nosgestesclimat-site/issues/723
> feat(t9n/en-us): take into account the feedback from UK students

- data/divers/divers.yaml
- data/i18n/t9n/translated-rules-en-us.yaml
@Clemog  @Benjamin-Boisserie-ABC j'ai essayé de simplifier avec moins de jargon car c'est grand public, et reformulé l'exemple.
> Proposition de reformulation de la notif de question objets divers

- data/alimentation/alimentation . boisson.yaml
- data/divers/divers . consommables.yaml
- data/i18n/models/PF-en-us.yaml
- data/i18n/models/PF-fr.yaml
- data/numérique/numérique.yaml
- data/transport/transport . voiture.yaml
- data/transport/transport.yaml
Suite à #1789 
Implémentation du mécanisme `moyenne` dans l'ensemble des règles
> Utilisation mécanisme moyenne

- package.json
- scripts/modelOptim.mjs
- scripts/rulesToJSON.mjs
- scripts/rulesToJSON.worker.mjs
- yarn.lock
Partially resolves #1812 by parallelizing the compilation of the model with workers through the package [`piscina`](https://www.npmjs.com/package/piscina).
For 16 regions and 2 languages, on:
```
CPU(s):                  8
On-line CPU(s) list:   0-7
Vendor ID:               GenuineIntel
Model name:            Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
CPU family:          6
Model:               142
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
Stepping:            10
CPU max MHz:         3400,0000
CPU min MHz:         400,0000
Caches (sum of all):     
L1d:                   128 KiB (4 instances)
L1i:                   128 KiB (4 instances)
L2:                    1 MiB (4 instances)
L3:                    6 MiB (1 instance)
```
| Command | Mean [s] | Min [s] | Max [s] …
> Feat(script/build): parallelizes the model compilation

- data/i18n/t9n/translated-rules-en-us.yaml
- data/transport/transport . avion.yaml
PR jumelle : https://github.com/datagir/nosgestesclimat-site/pull/948
> Modification des titres de questions avion

- data/transport/transport . avion.yaml
J'ai l'impression que c'est une erreur d'utiliser le mot "sur" ici ? 
En tout cas, une recherche sur google montre le peu d'usage, je n'ai pas trouvé de règles d'orthographe précise.
> Ces 3 dernières années, plutôt que "sur les" 3 dernières années

- data/i18n/t9n/translated-rules-en-us.yaml
- data/transport/transport . voiture.yaml
- personas/personas-fr.yaml
> Nouvelle règle de saisie voyageurs pour éviter la division par 0

- .github/workflows/upload-compilation-result.yaml
- scripts/modelOptim.mjs
- scripts/rulesToJSON.mjs
- scripts/rulesToJSON.worker.mjs
Closes https://github.com/datagir/nosgestesclimat-site/issues/985
> CI: break the workflow if an error occured in the rule compilation/optimisation pass

- scripts/i18n/check-translation.js
- scripts/i18n/cli.js
> feat(scripts/i18n): add 'all' option to remove all not up to date rule translations

- data/i18n/t9n/translated-rules-en-us.yaml
- data/transport/actions/transport.yaml
Fix #1879
(avec @JuliePouliquen)
> Action 5km voiture applicable si propriétaire

- data/transport/actions/transport.yaml
@JuliePouliquen, j'ai simplifié le code pour le publicodes des actions transport rapidement
Hésite pas à jeter un oeil :)
> Simplification publicodes actions Transport

- data/i18n/t9n/translated-rules-en-us.yaml
- data/transport/transport.yaml
Jusqu'à maintenant, aucune suggestion n'était proposé pour les kilomètres en deux-roues, je propose d'ajouter les mêmes que pour la voiture
> Ajout de suggestions pour les deux-roues

- data/divers/divers.yaml
> Oubli du montant dans la question dépenses de divers

- data/i18n/t9n/translated-rules-en-us.yaml
- data/logement/logement.yaml
- data/logement/vacances.yaml
Fix #1920 
Il manque la traduction de cette nouvelle structure du modèles mais qu'en pensez-vous ?
C'est clairement un hack, ça rend la partie profil sur cette question incompréhensible ..
> Fix: hack pour introduire une moyenne pour la mosaique vacances

- .github/ISSUE_TEMPLATE/retour-utilisateur.md
- CONTRIBUTING.md
- data/empreinte SDES/empreinte par branche.publicodes
- data/i18n/t9n/translated-rules-en-us.yaml
- scripts/services-societaux/input/répartition_services_sociétaux.yaml
Voir https://github.com/incubateur-ademe/nosgestesclimat-site/pull/1181
> Changement url `/contribuer`

- personas/personas-en-us.yaml
Petit oubli suite à #1968 
(Hésite pas à reprendre si certaines traductions ne conviennent pas @JuliePouliquen, je n'ai pas regardé en détail si tu avais fait des modifs)
> MAJ traduction personas

- personas/personas-en-us.yaml
- personas/personas-fr.yaml
Petits soucis d'affichage lié au tiret
> fix nom persona `Anne-Claire`

- data/actions.publicodes
- data/divers/actions/divers.publicodes
- data/divers/divers . tabac.publicodes
- data/divers/divers.publicodes
- data/i18n/t9n/translated-rules-en-us.yaml
- personas/personas-en-us.yaml
- personas/personas-fr.yaml
Fix #135 
Démo: https://nosgestesclimat.fr/simulateur/divers/tabac?PR=1995
Pour cette V1, on utilise un FE tiré de l'étude [Cigarette Smoking: An Assessment of Tobacco’s Global Environmental Footprint Across Its Entire Supply Chain](https://pubs.acs.org/doi/full/10.1021/acs.est.8b01533) qui donne une valeur de 14 gCO2e / cigarette.
En moyenne, par français :
>   D'après l'étude INSEE sur les [dépenses des ménages en 2017](https://www.insee.fr/fr/statistiques/4648319?sommaire=4648339), un ménage dépense en moyenne 402€ par an pour l'achat de tabac.
>      Le prix d'un paquet de cigarettes en 2017 était de [7,05 euros en moyenne](https://www.toutsurmesfinances.com/argent/a/prix-du-tabac-2017-2018-en-france-historique-et-augmentation).
>      Pour un ménage de 2,2 personnes (moyenne …
> 🚬 Ajout du tabac

- data/logement/logement.publicodes
- data/transport/transport . voiture.publicodes
Fix qui peut corriger le bug de mise à jour de la situation .. 🤔
> Fix: erreur publicodes saisie habitants

- data/i18n/t9n/translated-rules-en-us.yaml
- data/logement/piscine.publicodes
- data/transport/transport . ferry.publicodes
- package.json
- scripts/rulesToJSON.mjs
- yarn.lock
Closes https://github.com/incubateur-ademe/nosgestesclimat-site/issues/962.
- Uses the new `@incubateur-ademe/publicodes-tools@v0.2.0` API
- Import `piscine` module in the custom namespace `logement`
- Update translation (auto mode)
> refactor: use the new publicodes-tools getModelFromSource API

- data/i18n/t9n/translated-rules-en-us.yaml
- data/transport/transport . voiture.publicodes
Suite à https://github.com/incubateur-ademe/nosgestesclimat/pull/2049, la trad était manquante
> Fix traductions manquantes

- data/i18n/t9n/translated-rules-en-us.yaml
- yarn.lock
Suite à https://github.com/laem/futureco-data/pull/139
> feat: upgrade futureco-data

- data/alimentation/modèle déchets/alimentation . déchets.publicodes
- data/divers/divers . ameublement.publicodes
- data/divers/divers . loisirs . culture.publicodes
- data/divers/divers . textile.publicodes
- data/divers/divers . électroménager.publicodes
- data/i18n/t9n/translated-rules-en-us.yaml
- data/logement/vacances.publicodes
- data/numérique/numérique.publicodes
- data/transport/transport . mobilité douce.publicodes
- data/transport/transport.publicodes
- scripts/i18n/translate-rules.mjs
> feat: add suggestion "aucun"

- data/alimentation/alimentation.publicodes
> fix: oubli de l'attribut `formule`

- data/alimentation/alimentation . boisson.publicodes
- data/alimentation/alimentation.publicodes
> fix: choix non renseignés à 0 dans les suggestions de mosaiques

- data/i18n/t9n/translated-rules-en-us.yaml
- data/logement/climatisation.publicodes
- data/logement/logement.publicodes
- data/logement/piscine.publicodes
- data/logement/vacances.publicodes
- data/transport/transport . camping car.publicodes
- data/transport/transport . caravane.publicodes
> feat: l'amortissement du logement se fait sur chaque élément de la somme

- data/bilan.publicodes
- data/i18n/models/GF-en-us.yaml
- data/i18n/models/GF-fr.yaml
- data/i18n/models/GP-en-us.yaml
- data/i18n/models/GP-fr.yaml
- data/i18n/models/MQ-en-us.yaml
- data/i18n/models/MQ-fr.yaml
- data/i18n/models/PF-en-us.yaml
- data/i18n/models/PF-fr.yaml
- data/i18n/models/RE-en-us.yaml
- data/i18n/models/RE-fr.yaml
- data/i18n/models/YT-en-us.yaml
- data/i18n/models/YT-fr.yaml
- data/i18n/t9n/translated-rules-en-us.yaml
- data/transport/transport.publicodes
> fix: plus besoin de transport . empreinte

- data/actions/logement.publicodes
- data/i18n/t9n/translated-rules-en-us.yaml
- data/logement/logement.publicodes
Des modifications mineures qui doivent être dans preprod en vue de l'intégration de la version suisse
> Fix for ch version

- data/divers/animaux domestiques.publicodes
- data/i18n/t9n/translated-rules-en-us.yaml
Hot fix identifié par @Benjamin-Boisserie-ABC , on inversait les colonnes chats et chiens ..
> Fix: FE nourriture animaux domestiques (NGC-165)

- data/i18n/t9n/translated-rules-en-us.yaml
- data/logement/climatisation.publicodes
- data/services sociétaux/services marchands.publicodes
- data/services sociétaux/services publics.publicodes
- data/services sociétaux/services sociétaux.publicodes
Certaines abréviations posent problème dans l'implémentation du Ravijen
> Ajout/modification d'abréviations

- data/actions/logement.publicodes
- data/i18n/t9n/translated-rules-en.yaml
- data/logement/chauffage.publicodes
- data/logement/prix du bois.publicodes
- personas/personas-en.yaml
- personas/personas-fr.yaml
> Fix bug aide à la saisie bois (NGC-210)

- data/alimentation/repas.publicodes
- data/bilan.publicodes
- data/logement/chauffage.publicodes
Utile pour la landing de la documentation
> Ajout d'icones manquants

- data/actions/alimentation.publicodes
- data/actions/logement.publicodes
- data/actions/transport.publicodes
- data/divers/loisirs.publicodes
- data/logement/chauffage.publicodes
- data/logement/vacances.publicodes
- data/logement/électricité.publicodes
https://preprod.nosgestesclimat.fr/?PR=2205
> Fix conditions actions (NGC-142)

- data/actions/transport.publicodes
- data/i18n/t9n/translated-rules-en.yaml
- data/transport/voiture.publicodes
- personas/personas-fr.yaml
-> Diff pour corentin : on passe du gabarit "moyenne" à "berline" pour l'empreinte "par défaut" de la voiture (utilisateur non régulier)
-> Diff pour Sandy : on considère quelle ne connait pas les caractéristiques de sa voiture donc voiture "moyenne" utilisateur régulier
> Fix: questions "je ne sais pas" voiture (NGC-427)

- data/alimentation/boisson.publicodes
- data/i18n/t9n/translated-rules-en.yaml
- personas/personas-fr.yaml
Ceci afin de pouvoir proposer dans les actions un remplacement d'une partie des cafés bus par de la chicorée.
> Ajout de la chicorée parmi les boissons chaudes (NGC-433)

- package.json
- tests/commons.mjs
- yarn.lock
Related PR: https://github.com/publicodes/tools/pull/33
> Fix(build): patch `@publicodes/tools`

- scripts/rulesToJSON.mjs
@JuliePouliquen je vois qu'on ne gérait pas du tout les unités pour les actions ;) On aura désormais l'erreur dans la console!
> feat: add check for action units

- data/actions/actions.publicodes
- data/actions/divers.publicodes
- data/divers/textile.publicodes
- data/i18n/t9n/translated-rules-en.yaml
- data/transport/train.publicodes
Actions à ajouter : 
- Textile
- Conso produits neufs
- Édition
- Sports
- Produits d'hygiène
> Nouvelles actions divers - NGC-306 / NGC-483

- data/i18n/models/NC-en.publicodes
- data/i18n/models/NC-fr.publicodes
Pour permettre la contribution pour la version neo calédonienne
> Ajoute la nouvelle calédonie

- data/alimentation/repas.publicodes
- data/i18n/t9n/translated-rules-en.yaml
Explique mieux que de manière standard on mange 14 repas par semaine, mais ça peut être plus, ou moins.
> Modifications de textes au niveau des repas par semaine - NGC-442

- data/transport/voiture.publicodes
> Ajout du GPL - NGC-505

- data/i18n/t9n/translated-rules-en.yaml
- package.json
- scripts/i18n/addTranslationToBaseRules.js
- yarn.lock
> Support empty rules trad

- data/actions/alimentation.publicodes
- data/actions/divers.publicodes
Fix errors introduced when rebasing while after refactoring `recalcul` as `contexte`.
> fix(data): remove forgotten 'formule'

- data/actions/actions.publicodes
- data/actions/logement.publicodes
- data/i18n/models/CH-en.publicodes
- data/i18n/models/CH-fr.publicodes
- data/i18n/t9n/translated-rules-en.yaml
> Suppression action LED - NGC-593

- .prettierrc
- package.json
- quick-doc/.eslintrc.cjs
- quick-doc/index.html
- quick-doc/package.json
- quick-doc/postcss.config.js
- quick-doc/src/App.css
- quick-doc/src/App.tsx
- quick-doc/src/AppContext.tsx
- quick-doc/src/Documentation.tsx
- quick-doc/src/Personas.tsx
- quick-doc/src/index.css
- quick-doc/tailwind.config.js
- quick-doc/vite.config.ts
- quick-doc/yarn.lock
- yarn.lock
- Setup context with provider/reducer to handle situation changes
- Setup tailwindcss for minimal style
> feat(quick-doc)!: allow to switch between personas' situation - [NGC-625]

- package.json
- quick-doc/package.json
- quick-doc/yarn.lock
- scripts/rulesToJSON.mjs
- yarn.lock
> [!CAUTION]
> ~~There is an issue with the latest version of publicodes! The `transport . ferry` is not evaluated as expected -- see https://mattermost.incubateur.net/betagouv/pl/mc6gg1sobige9jq7f9jz81tday~~ SOLVED
> pkg!: upgrade all publicodes deps and add as a peerdep

- package.json
- prepack.mjs
- scripts/migrationToJSON.mjs
- scripts/rulesToJSON.mjs
Ajout d'un export `models` qui contient un objet avec tous les modèles
> Fix model fetching

- data/actions/alimentation.publicodes
- data/actions/divers.publicodes
- data/actions/logement.publicodes
- data/actions/services sociétaux.publicodes
- data/actions/transport/avion.publicodes
- data/actions/transport/boulot.publicodes
- data/actions/transport/deux roues.publicodes
- data/actions/transport/voiture.publicodes
- data/alimentation/boisson.publicodes
- data/i18n/t9n/translated-rules-en.yaml
- data/i18n/t9n/translated-rules-es.yaml
> Réécriture des actions suite relecture ADEME NGC-800 NGC-685

- data/i18n/t9n/translated-rules-en.yaml
- data/i18n/t9n/translated-rules-es.yaml
- data/ui/pédagogie.publicodes
- scripts/modelOptim.mjs
Je suis obligé d'ajouter le règle dans la whitelist pour l'optim. J'imagine que j'ai raté un truc ?
> Actions pour les empreintes < 4 tonnes [NGC-814] 

- data/actions/logement.publicodes
- data/i18n/models/CH-en.publicodes
- data/i18n/models/CH-es.publicodes
- data/i18n/models/CH-fr.publicodes
- data/i18n/t9n/translated-rules-en.yaml
- data/i18n/t9n/translated-rules-es.yaml
- data/logement/chiffres parc logements français.publicodes
- data/logement/électricité.publicodes
- data/transport/voiture.publicodes
- data/ui/organisations.publicodes
- migration/migration.yaml
- personas/personas-fr.yaml
- scripts/modelOptim.mjs
La question PV apparait apres la conso d'élec mais à priori, on n'a pas besoin de la conso si 100% d'autoconso.. donc la question PV devrait apparaitre avant
> Photovoltaique nouvelle proposition (NGC-560)

- data/i18n/models/US-en.publicodes
- data/i18n/models/US-es.publicodes
- data/i18n/models/US-fr.publicodes
- data/i18n/t9n/translated-rules-en.yaml
- data/i18n/t9n/translated-rules-es.yaml
- data/logement/logement.publicodes
- data/transport/métro ou tram.publicodes
Correction de traductions, du prix au kWh pour les US, et correction pour tout le monde de "RER" en "train de banlieue"
> Modifs branche us - NGC-828

- data/i18n/t9n/translated-rules-en.yaml
- data/i18n/t9n/translated-rules-es.yaml
- data/transport/voiture.publicodes
⚠️ Bug publicodes remonté ici https://github.com/publicodes/publicodes/issues/517
> MAJ calcul des km annuels (NGC-1035)

- data/i18n/t9n/translated-rules-en.yaml
- data/i18n/t9n/translated-rules-es.yaml
- data/transport/transports commun.publicodes
Modifie suggestions pour tous les transports en commun.
> Transports commun suggestions - NGC-950

- data/i18n/t9n/translated-rules-en.yaml
- data/i18n/t9n/translated-rules-es.yaml
- data/services sociétaux/services sociétaux.publicodes
> fix texte services sociétaux - NGC-994

- data/actions/logement.publicodes
- data/i18n/t9n/translated-rules-en.yaml
- data/i18n/t9n/translated-rules-es.yaml
- data/logement/piscine.publicodes
> Fix bugs modèle NGC-1111 NGC-1130

- data/alimentation/boisson.publicodes
Simple changement des facteurs d'émission grâce à la nouvelle version des données Agribalyse.
> Implé données Agribalyse 3.2 boissons NGC-1230

- data/i18n/models/CH-en.publicodes
- data/i18n/models/CH-es.publicodes
- data/i18n/models/CH-fr.publicodes
- data/transport/voiture.publicodes
Enlève "par défaut" pour la voiture
Corrige une note de la version suisse sur la pompe à chaleur
> Fix release

- .github/workflows/upload-compilation-result.yaml
- .gitignore
- index.d.ts
- package.json
Hello, petite PR qui permet d'exposer le bon type `DottedName` à partir des types générés dans `types/` avec `prepack.mjs`.
> fix(package): correctly import generated types

- data/actions/logement.publicodes
- data/alimentation/alimentation.publicodes
- data/bilan.publicodes
- data/i18n/t9n/translated-rules-en.yaml
- data/i18n/t9n/translated-rules-es.yaml
Ici je modifie trois titres H3 en H2 pour respecter la règle d'accessibilité qui demande que la hiérarchie de titres dans chaque page soit cohérente (augmente de 1 en 1)
> ♻️ Change title type in desc to avoid breaking a11y rule

- data/logement/prix du gaz.publicodes
- index.d.ts
- package.json
- quick-doc/package.json
- quick-doc/src/AppContext.ts
- quick-doc/yarn.lock
- yarn.lock
Waiting for https://github.com/publicodes/publicodes/pull/662
> 🐛 fix types

- .github/workflows/upload-compilation-result.yaml
- data/actions/transport/boulot.publicodes
- data/actions/transport/voiture.publicodes
- data/i18n/t9n/translated-rules-en.yaml
- data/i18n/t9n/translated-rules-es.yaml
- data/logement/logement.publicodes
- data/transport/vacances.publicodes
- data/transport/voiture.publicodes
- package.json
- personas/personas-fr.yaml
* feat: utilisateur devient la première question
* feat: new wording
* fix: voiture ne peut pas être désactivée
* feat: traduction
* fix: continuous release comment update
* fix: rebase
* v3.9.0-rc.1
* v3.9.0-rc.2
* v3.9.0-rc.3
* Update package.json
---------
> 🔖 Release 3.9.0
